
# zeekeeper配置
zookeeper:
  server: 127.0.0.1:2181 # 服务器列表，格式host1:port1,host2:port2,...
  sessionTimeoutMs: 6000 # 会话超时时间，单位毫秒，默认60000ms
  connectionTimeoutMs: 6000 # 连接创建超时时间，单位毫秒，默认60000ms
  maxRetries: 3 # 当连接异常时的重试次数
  baseSleepTimeMs: 1000 # 重试之间等待的初始时间
  namespace: lock
server:
  port: 8090
